---
# - include: composer_install.yml tags=cakephp3
#
# - include: configure.yml        tags=cakephp3
#
#
# - name: execution check / edit_boostrap
#   shell: "grep \".\ DS\ .\ 'bootstrap'\ .\ DS\ .\ 'environments.php'\" bootstrap.php"
#   register: edit_bootstrap
#   failed_when: edit_bootstrap.rc not in [0, 1]
#   args:
#     chdir: "{{ cakephp3_project_dir }}/config"
#
# - include: edit_bootstrap.yml   tags=cakephp3
#   when: edit_bootstrap.rc == 1
#
#
# - include: edit_app.yml         tags=cakephp3
#
 - include: test_env_access_nginx.yml         tags=cakephp3
